// js/data.js
const recitersData = [
    { id: "abdullah-ali-jabir", name: "Abdullah Ali Jabir", riwaya: "Hafs an Asim", category: "Hafs", image: "images/abdullah-ali-jabir.jpg", audioBasePath: "audio/Abdullah Ali Jabir/", bio: "Sheikh Abdullah Ali Jabir (1953 – 2006) was a renowned Imam and Khatib of the Masjid al-Haram in Makkah. He was known for his beautiful and emotional Quranic recitation. <br><em>(Bio can be expanded or replaced)</em>" },
    { id: "abu-bakr-al-shatri", name: "Abu Bakr al-Shatri", riwaya: "Hafs an Asim", category: "Hafs", image: "images/abu-bakr-al-shatri.jpg", audioBasePath: "audio/abu-bakr-al-shatri/", bio: "Abu Bakr Ibn Muhammad Al Shatri, born in Jeddah in 1970, is a respected Saudi Quran reciter. He is known for his clear and melodious voice. <br><em>(Bio can be expanded or replaced)</em>" },
    { id: "saad-al-ghamdi", name: "Saad al-Ghamdi", riwaya: "Hafs an Asim", category: "Hafs", image: "images/saad-al-ghamdi.jpg", audioBasePath: "audio/saad-al-ghamdi/", bio: "Sheikh Saad Al-Ghamdi (born 1967) is a Quran reciter and an Imam from Dammam, Saudi Arabia. His recitations are widely popular across the globe. <br><em>(Bio can be expanded or replaced)</em>" },
    { id: "salah-bukhatir", name: "Salah Bukhatir", riwaya: "Hafs an Asim", category: "Hafs", image: "images/salah-bukhatir.jpg", audioBasePath: "audio/salah-bukhatir/", bio: "Salah Bukhatir is an Imam and Quran reciter from the United Arab Emirates. He is known for his deeply moving and distinct style of recitation. <br><em>(Bio can be expanded or replaced)</em>" },
    { id: "abdulbaset-warsh", name: "AbdulBaset AbdulSamad", riwaya: "Warsh an Nafi'", category: "Non-Hafs", image: "images/abdulbaset-warsh.jpg", audioBasePath: "audio/abdulbaset-warsh/", bio: "Qari Abdul-Basit 'Abdus-Samad (1927–1988) was an Egyptian Qari, widely regarded as one of the best reciters of the Quran of all time. This collection features his Warsh recitation. <br><em>(Bio can be expanded or replaced)</em>" },
    { id: "sufi-doori", name: "Abdur-Rashid Sufi", riwaya: "Ad-Doori an Abi Amr", category: "Non-Hafs", image: "images/sufi-doori.jpg", audioBasePath: "audio/sufi-doori/", bio: "Abdur-Rashid Ali Sufi is a Somali Quran reciter known for his expertise in various Qira'at. This collection is his recitation in Ad-Doori 'an Abi 'Amr. <br><em>(Bio can be expanded or replaced)</em>" },
    { id: "sufi-shubah", name: "Abdur-Rashid Sufi", riwaya: "Shu'bah an Asim", category: "Non-Hafs", image: "images/sufi-shubah.jpg", audioBasePath: "audio/sufi-shubah/", bio: "Another beautiful collection from Abdur-Rashid Ali Sufi, this time in the Riwaya of Shu'bah 'an Asim. <br><em>(Bio can be expanded or replaced)</em>" },
    { id: "huthaify-qaloon", name: "Ali al-Huthaify", riwaya: "Qaloon an Nafi'", category: "Non-Hafs", image: "images/huthaify-qaloon.jpg", audioBasePath: "audio/huthaify-qaloon/", bio: "Sheikh Ali Abdur-Rahman al-Huthaify is a well-known Imam and Khatib of the Prophet's Mosque in Madinah. This is his recitation in Qaloon 'an Nafi'. <br><em>(Bio can be expanded or replaced)</em>" }
];

const surahData = [
    { "id": 1, "name": "Al-Fatiha", "arabic": "ٱلْفَاتِحَة", "ayahs": 7 }, { "id": 2, "name": "Al-Baqarah", "arabic": "ٱلْبَقَرَة", "ayahs": 286 },
    { "id": 3, "name": "Aal-E-Imran", "arabic": "آلِ عِمْرَان", "ayahs": 200 }, { "id": 4, "name": "An-Nisa", "arabic": "ٱلنِّسَاء", "ayahs": 176 },
    { "id": 5, "name": "Al-Ma'idah", "arabic": "ٱلْمَائِدَة", "ayahs": 120 }, { "id": 6, "name": "Al-An'am", "arabic": "ٱلْأَنْعَام", "ayahs": 165 },
    { "id": 7, "name": "Al-A'raf", "arabic": "ٱلْأَعْرَاف", "ayahs": 206 }, { "id": 8, "name": "Al-Anfal", "arabic": "ٱلْأَنْفَال", "ayahs": 75 },
    { "id": 9, "name": "At-Tawbah", "arabic": "ٱلتَّوْبَة", "ayahs": 129 }, { "id": 10, "name": "Yunus", "arabic": "يُونُس", "ayahs": 109 },
    { "id": 11, "name": "Hud", "arabic": "هُود", "ayahs": 123 }, { "id": 12, "name": "Yusuf", "arabic": "يُوسُف", "ayahs": 111 },
    { "id": 13, "name": "Ar-Ra'd", "arabic": "ٱلرَّعْد", "ayahs": 43 }, { "id": 14, "name": "Ibrahim", "arabic": "إِبْرَاهِيم", "ayahs": 52 },
    { "id": 15, "name": "Al-Hijr", "arabic": "ٱلْحِجْر", "ayahs": 99 }, { "id": 16, "name": "An-Nahl", "arabic": "ٱلنَّحْل", "ayahs": 128 },
    { "id": 17, "name": "Al-Isra", "arabic": "ٱلْإِسْرَاء", "ayahs": 111 }, { "id": 18, "name": "Al-Kahf", "arabic": "ٱلْكَهْف", "ayahs": 110 },
    { "id": 19, "name": "Maryam", "arabic": "مَرْيَم", "ayahs": 98 }, { "id": 20, "name": "Taha", "arabic": "طه", "ayahs": 135 },
    { "id": 21, "name": "Al-Anbiya", "arabic": "ٱلْأَنْبِيَاء", "ayahs": 112 }, { "id": 22, "name": "Al-Hajj", "arabic": "ٱلْحَجّ", "ayahs": 78 },
    { "id": 23, "name": "Al-Mu'minun", "arabic": "ٱلْمُؤْمِنُون", "ayahs": 118 }, { "id": 24, "name": "An-Nur", "arabic": "ٱلنُّور", "ayahs": 64 },
    { "id": 25, "name": "Al-Furqan", "arabic": "ٱلْفُرْقَان", "ayahs": 77 }, { "id": 26, "name": "Ash-Shu'ara", "arabic": "ٱلشُّعَرَاء", "ayahs": 227 },
    { "id": 27, "name": "An-Naml", "arabic": "ٱلنَّمْل", "ayahs": 93 }, { "id": 28, "name": "Al-Qasas", "arabic": "ٱلْقَصَص", "ayahs": 88 },
    { "id": 29, "name": "Al-Ankabut", "arabic": "ٱلْعَنْكَبُوت", "ayahs": 69 }, { "id": 30, "name": "Ar-Rum", "arabic": "ٱلرُّوم", "ayahs": 60 },
    { "id": 31, "name": "Luqman", "arabic": "لُقْمَان", "ayahs": 34 }, { "id": 32, "name": "As-Sajdah", "arabic": "ٱلسَّجْدَة", "ayahs": 30 },
    { "id": 33, "name": "Al-Ahzab", "arabic": "ٱلْأَحْزَاب", "ayahs": 73 }, { "id": 34, "name": "Saba", "arabic": "سَبَأ", "ayahs": 54 },
    { "id": 35, "name": "Fatir", "arabic": "فَاطِر", "ayahs": 45 }, { "id": 36, "name": "Ya-Sin", "arabic": "يس", "ayahs": 83 },
    { "id": 37, "name": "As-Saffat", "arabic": "ٱلصَّافَّات", "ayahs": 182 }, { "id": 38, "name": "Sad", "arabic": "ص", "ayahs": 88 },
    { "id": 39, "name": "Az-Zumar", "arabic": "ٱلزُّمَر", "ayahs": 75 }, { "id": 40, "name": "Ghafir", "arabic": "غَافِر", "ayahs": 85 },
    { "id": 41, "name": "Fussilat", "arabic": "فُصِّلَت", "ayahs": 54 }, { "id": 42, "name": "Ash-Shura", "arabic": "ٱلشُّورَىٰ", "ayahs": 53 },
    { "id": 43, "name": "Az-Zukhruf", "arabic": "ٱلزُّخْرُف", "ayahs": 89 }, { "id": 44, "name": "Ad-Dukhan", "arabic": "ٱلدُّخَان", "ayahs": 59 },
    { "id": 45, "name": "Al-Jathiyah", "arabic": "ٱلْجَاثِيَة", "ayahs": 37 }, { "id": 46, "name": "Al-Ahqaf", "arabic": "ٱلْأَحْقَاف", "ayahs": 35 },
    { "id": 47, "name": "Muhammad", "arabic": "مُحَمَّد", "ayahs": 38 }, { "id": 48, "name": "Al-Fath", "arabic": "ٱلْفَتْح", "ayahs": 29 },
    { "id": 49, "name": "Al-Hujurat", "arabic": "ٱلْحُجُرَات", "ayahs": 18 }, { "id": 50, "name": "Qaf", "arabic": "ق", "ayahs": 45 },
    { "id": 51, "name": "Adh-Dhariyat", "arabic": "ٱلذَّارِيَات", "ayahs": 60 }, { "id": 52, "name": "At-Tur", "arabic": "ٱلطُّور", "ayahs": 49 },
    { "id": 53, "name": "An-Najm", "arabic": "ٱلنَّجْم", "ayahs": 62 }, { "id": 54, "name": "Al-Qamar", "arabic": "ٱلْقَمَر", "ayahs": 55 },
    { "id": 55, "name": "Ar-Rahman", "arabic": "ٱلرَّحْمَٰن", "ayahs": 78 }, { "id": 56, "name": "Al-Waqi'ah", "arabic": "ٱلْوَاقِعَة", "ayahs": 96 },
    { "id": 57, "name": "Al-Hadid", "arabic": "ٱلْحَدِيد", "ayahs": 29 }, { "id": 58, "name": "Al-Mujadilah", "arabic": "ٱلْمُجَادِلَة", "ayahs": 22 },
    { "id": 59, "name": "Al-Hashr", "arabic": "ٱلْحَشْر", "ayahs": 24 }, { "id": 60, "name": "Al-Mumtahanah", "arabic": "ٱلْمُمْتَحَنَة", "ayahs": 13 },
    { "id": 61, "name": "As-Saff", "arabic": "ٱلصَّفّ", "ayahs": 14 }, { "id": 62, "name": "Al-Jumu'ah", "arabic": "ٱلْجُمُعَة", "ayahs": 11 },
    { "id": 63, "name": "Al-Munafiqun", "arabic": "ٱلْمُنَافِقُون", "ayahs": 11 }, { "id": 64, "name": "At-Taghabun", "arabic": "ٱلتَّغَابُن", "ayahs": 18 },
    { "id": 65, "name": "At-Talaq", "arabic": "ٱلطَّلَاق", "ayahs": 12 }, { "id": 66, "name": "At-Tahrim", "arabic": "ٱلتَّحْرِيم", "ayahs": 12 },
    { "id": 67, "name": "Al-Mulk", "arabic": "ٱلْمُلْك", "ayahs": 30 }, { "id": 68, "name": "Al-Qalam", "arabic": "ٱلْقَلَم", "ayahs": 52 },
    { "id": 69, "name": "Al-Haqqah", "arabic": "ٱلْحَاقَّة", "ayahs": 52 }, { "id": 70, "name": "Al-Ma'arij", "arabic": "ٱلْمَعَارِج", "ayahs": 44 },
    { "id": 71, "name": "Nuh", "arabic": "نُوح", "ayahs": 28 }, { "id": 72, "name": "Al-Jinn", "arabic": "ٱلْجِنّ", "ayahs": 28 },
    { "id": 73, "name": "Al-Muzzammil", "arabic": "ٱلْمُزَّمِّل", "ayahs": 20 }, { "id": 74, "name": "Al-Muddaththir", "arabic": "ٱلْمُدَّثِّر", "ayahs": 56 },
    { "id": 75, "name": "Al-Qiyamah", "arabic": "ٱلْقِيَامَة", "ayahs": 40 }, { "id": 76, "name": "Al-Insan", "arabic": "ٱلْإِنْسَان", "ayahs": 31 },
    { "id": 77, "name": "Al-Mursalat", "arabic": "ٱلْمُرْسَلَات", "ayahs": 50 }, { "id": 78, "name": "An-Naba", "arabic": "ٱلنَّبَأ", "ayahs": 40 },
    { "id": 79, "name": "An-Nazi'at", "arabic": "ٱلنَّازِعَات", "ayahs": 46 }, { "id": 80, "name": "Abasa", "arabic": "عَبَسَ", "ayahs": 42 },
    { "id": 81, "name": "At-Takwir", "arabic": "ٱلتَّكْوِير", "ayahs": 29 }, { "id": 82, "name": "Al-Infitar", "arabic": "ٱلْإِنْفِطَار", "ayahs": 19 },
    { "id": 83, "name": "Al-Mutaffifin", "arabic": "ٱلْمُطَفِّفِين", "ayahs": 36 }, { "id": 84, "name": "Al-Inshiqaq", "arabic": "ٱلْإِنْشِقَاق", "ayahs": 25 },
    { "id": 85, "name": "Al-Buruj", "arabic": "ٱلْبُرُوج", "ayahs": 22 }, { "id": 86, "name": "At-Tariq", "arabic": "ٱلطَّارِق", "ayahs": 17 },
    { "id": 87, "name": "Al-Ala", "arabic": "ٱلْأَعْلَىٰ", "ayahs": 19 }, { "id": 88, "name": "Al-Ghashiyah", "arabic": "ٱلْغَاشِيَة", "ayahs": 26 },
    { "id": 89, "name": "Al-Fajr", "arabic": "ٱلْفَجْر", "ayahs": 30 }, { "id": 90, "name": "Al-Balad", "arabic": "ٱلْبَلَد", "ayahs": 20 },
    { "id": 91, "name": "Ash-Shams", "arabic": "ٱلشَّمْس", "ayahs": 15 }, { "id": 92, "name": "Al-Layl", "arabic": "ٱللَّيْل", "ayahs": 21 },
    { "id": 93, "name": "Ad-Duha", "arabic": "ٱلضُّحَىٰ", "ayahs": 11 }, { "id": 94, "name": "Ash-Sharh", "arabic": "ٱلشَّرْح", "ayahs": 8 },
    { "id": 95, "name": "At-Tin", "arabic": "ٱلتِّين", "ayahs": 8 }, { "id": 96, "name": "Al-Alaq", "arabic": "ٱلْعَلَق", "ayahs": 19 },
    { "id": 97, "name": "Al-Qadr", "arabic": "ٱلْقَدْر", "ayahs": 5 }, { "id": 98, "name": "Al-Bayyinah", "arabic": "ٱلْبَيِّنَة", "ayahs": 8 },
    { "id": 99, "name": "Az-Zalzalah", "arabic": "ٱلزَّلْزَلَة", "ayahs": 8 }, { "id": 100, "name": "Al-Adiyat", "arabic": "ٱلْعَادِيَات", "ayahs": 11 },
    { "id": 101, "name": "Al-Qari'ah", "arabic": "ٱلْقَارِعَة", "ayahs": 11 }, { "id": 102, "name": "At-Takathur", "arabic": "ٱلتَّكَاثُر", "ayahs": 8 },
    { "id": 103, "name": "Al-Asr", "arabic": "ٱلْعَصْر", "ayahs": 3 }, { "id": 104, "name": "Al-Humazah", "arabic": "ٱلْهُمَزَة", "ayahs": 9 },
    { "id": 105, "name": "Al-Fil", "arabic": "ٱلْفِيل", "ayahs": 5 }, { "id": 106, "name": "Quraysh", "arabic": "قُرَيْش", "ayahs": 4 },
    { "id": 107, "name": "Al-Ma'un", "arabic": "ٱلْمَاعُون", "ayahs": 7 }, { "id": 108, "name": "Al-Kawthar", "arabic": "ٱلْكَوْثَر", "ayahs": 3 },
    { "id": 109, "name": "Al-Kafirun", "arabic": "ٱلْكَافِرُون", "ayahs": 6 }, { "id": 110, "name": "An-Nasr", "arabic": "ٱلنَّصْر", "ayahs": 3 },
    { "id": 111, "name": "Al-Masad", "arabic": "ٱلْمَسَد", "ayahs": 5 }, { "id": 112, "name": "Al-Ikhlas", "arabic": "ٱلْإِخْلَاص", "ayahs": 4 },
    { "id": 113, "name": "Al-Falaq", "arabic": "ٱلْفَلَق", "ayahs": 5 }, { "id": 114, "name": "An-Nas", "arabic": "ٱلنَّاس", "ayahs": 6 }
];